global:
  scrape_interval: 10s

# metrics_path defaults to '/metrics'
# scheme defaults to 'http'.
scrape_configs:
  - job_name: "gnmic"
    static_configs:
      - targets: ["clab-srv6-flexalgo-gnmic:98${GROUP_ID}4"]
    #consul_sd_configs:
    #- server: 192.168.1.131:8500
